name: Mirror to Public

on:
  push:
    branches: [ master, main, dev ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no persistas credenciales)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # 👈 clave

      # Cinturón y tirantes: borra el header que mete checkout a nivel global
      - name: Remove GITHUB_TOKEN extraheader
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true

      - name: Configure git
        run: |
          git config user.name  "expolicores-bot"
          git config user.email "bot@users.noreply.github.com"

      - name: Add mirror remote (with PAT)
        run: |
          git remote remove mirror 2>/dev/null || true
          git remote add mirror "https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/expolicores/expolicores-app-public.git"
          git remote -v

      - name: Push current branch to mirror
        run: |
          echo "Pushing ${{ github.ref_name }} -> mirror/${{ github.ref_name }}"
          git push --force-with-lease mirror "${{ github.ref_name }}:${{ github.ref_name }}"
