name: Mirror all branches to Public Repo

on:
  push:
    branches:
      - '**'  # Todas las ramas

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Trae todo el historial
          persist-credentials: false

      - name: Setup SSH key for access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust GitHub host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add mirror remote and push
        run: |
          git remote add mirror git@github.com:expolicores/expolicores-app-public.git
          echo "Pushing all branches and tags to mirror..."
          git push --prune --force --tags mirror "refs/remotes/origin/*:refs/heads/*"

      - name: Post Setup SSH key for access
        run: |
          ssh-add -D
