name: Mirror to Public (SSH)

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  mirror:
    if: ${{ github.repository == 'expolicores/expolicores-app' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH key for pushing
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_SSH_KEY }}

      - name: Trust GitHub.com host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add mirror remote (SSH)
        run: |
          git remote add mirror git@github.com:expolicores/expolicores-app-public.git
          git remote -v

      - name: Push current branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push --force-with-lease mirror "$BRANCH:$BRANCH"

      - name: Push tags (optional)
        run: |
          git push mirror --tags
